name: Update index.html

on:
  push:
    paths:
      - 'usr_upload/**'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files and generate index.html
        run: |
          echo "<html><body><h1>Files in usr_upload/</h1><ul>" > usr_upload/index.html
          for file in usr_upload/*; do
            echo "<li><a href='$file'>$(basename $file)</a></li>" >> usr_upload/index.html
          done
          echo "</ul></body></html>" >> usr_upload/index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "LMBpultd0"
          git config --global user.email "web.lmbpultd.2023@gmail.com"
          git add usr_upload/index.html
          git commit -m "Automatically updated index.html"
          git push
